### ISSUE TITLE
Citing charnley/rmsd (with a DOI)

### ISSUE THREAD

**Issue by bertrand-caron** [charnley/rmsd#38]
Hi Jimmy,

Thanks a lot for having written (and distributing) `charnley/rmsd`. I have used your code as part of my PhD work and am looking at the best way of citing your work. Have you considered starting using [Zenodo](https://zenodo.org) on your project? This would automatically give you a DOI for every release, and is very easy to set up.

Thanks, Bertrand

**Comment by charnley** [comment]
Hi Bertrand,

In regards to Zenodo I have mixed feelings about the service.
I want to make sure that contributors get recognition for their contribution to the, but when using Zenodo, it will use github usernames of no names are associated with the profile. 

I did create a zenodo doi a while back (https://zenodo.org/record/1251123) I just did not link it anywhere. For now I have just told people to cite rmsd as the following, but as long as you cite with the github link its all good to me.

> Calculate Root-mean-square deviation (RMSD) of Two Molecules Using Rotation, GitHub, http://github.com/charnley/rmsd, version

Hi main contributors, 
@larsbratholm @benjfitz @cstein @KPLauritzen @andersx @Ashafix 
Since I didn't make all the code my self, any input / preference for official RMSD citation are welcome.
