### ISSUE TITLE
error: Structures not same size

### ISSUE THREAD

**Issue by senjoro** [charnley/rmsd#70]
Sorry to bother you with this little problem
The two PDB files I want to compare have different sizes
"error: Structures not same size"  what this means is that the two structures size need same ?

**Comment by nbehrnd** [comment]
The easiest reason why the implementation of Kabsch and Quaternion
approach by calculate_rmsd.py will fail is if the number of atoms in
model A differs from the one in model B; i.e., the program is not
able to compare propane.xyz with butane.xyz.

This constraint applies to structures described in either .xyz, or
.pdb format.  Because the superposition and alignment of two
structures seeks to consider for each atom in model A an equivalent
in model B, processing models of different size otherwise could yield
a situation where an atom in the reference structure has no
equivalence in the test structure.

If you want to stick to .pdb without edit of the structures (e.g.,
truncation of one chain), possibly PyMol is one program to align
protein structures based on what their sequences share with each other.

**Comment by charnley** [comment]
@senjoro 

It is not possible to calculate RMSD between two different molecules, e.i. "compare PDB files with differen sizes".  See https://en.wikipedia.org/wiki/Root-mean-square_deviation_of_atomic_positions. In short, you need atom-pairs. If you are looking for chemical similarity between two molecules, then I suggest you look at RDKit.

For RMSD, select the substructure in your PDB's you know are the same, store them as a separate files, and run rmsd on those to compare.
