### ISSUE TITLE
msg = f"error: Parsing atomtype for the following line:" f" \n{line}"

### ISSUE THREAD

**Issue by brielletilson** [charnley/rmsd#73]
Tried downloading the code and running it in the command line. This is what I got?

./calculate_rmsd.py pablo3a.xyz pablo3b.xyz 
  File "./calculate_rmsd.py", line 1467
    msg = f"error: Parsing atomtype for the following line:" f" \n{line}"
                                                           ^
SyntaxError: invalid syntax

Would you help me understand what this means?

**Comment by benjfitz** [comment]
Hi there,
Would you please attach the 2 xyz files?
Thanks,
Benj

**Comment by brielletilson** [comment]
Attached.

**Comment by charnley** [comment]
Hi @brielletilson, what Python version are you using? The file requires Python 3.x for the format style.

But you probably also have format problem in the xyz file. Could you paste the content on github as well?

**Comment by brielletilson** [comment]
Okay I updated the python version (I was used 2.7 I believe) but now I am having problems with bumpy. I updated that to the newest version but still am getting an error message when I try running the script:

Brielles-MacBook-Air:rmsd brielletilson$ pip3 install numpy
Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (1.20.1)
Brielles-MacBook-Air:rmsd brielletilson$ python3 ./calculate_rmsd.py pablo3a.xyz pablo3b.xyz 
Traceback (most recent call last):
  File "./calculate_rmsd.py", line 19, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Brielles-MacBook-Air:rmsd brielletilson$

**Comment by brielletilson** [comment]
[
[pablo3a.txt](https://github.com/charnley/rmsd/files/6018836/pablo3a.txt)
[pablo3b.txt](https://github.com/charnley/rmsd/files/6018837/pablo3b.txt)

](url)

**Comment by brielletilson** [comment]
Wow I cannot type apparently, sorry!

*I was using 2.7 I believe* and *numpy* not bumpy. 🙄

**Comment by nbehrnd** [comment]
Three points to note:

+ Calculate_rmsd.py expects the input files to be either both `.xyz`,
  or both `.pdb`.  This  applies both to the files' content and
  syntax, as well as to the file names' extension.  Thus,
  `Pablo3a.txt` is not ok.  In addition, to be a valid `.xyz` for the
  computation, the header in this file is missing, i.e. a statement
  of the number of atoms and a title line (which may be empty, but
  better would name the molecule to trace your work in the long run.

+ Except there is a very good reason, start new projects with Python3
  only.  A current version would be 3.9.1.  If you are not
  comfortable or not permitted to install the interpreter on the
  computer at your disposition, try an installation free approach
  to access a Python interpreter like WinPython (for Windows) running
  from a thumb drive, or an online service like repl.it running on a
  remote server.  For the later: Check first if you are allowed to
  transfer confidential data to an other computer.

+ The atoms in both .xyz are not in order.  But this is no problem
  because the script may sort this out for you.  A well maintained
  installation of current Python3.9 (including matplotlib and
  scipy) yields for an input of 

  `python calculate_rmsd.py pablo3aa.xyz pablo3b.xyz --reorder`

  the output of

  `2.245415496229203`

**Comment by nbehrnd** [comment]
In GitHub, the reply by e-mail does not support the normal markdown syntax.  Thus now for reference
the files processed successfully:
[files_of_comparison.zip](https://github.com/charnley/rmsd/files/6018926/files_of_comparison.zip)

And entries for either [WinPython](https://winpython.github.io/), and [repl.it](https://repl.it/) as alternatives should an installation of Python3 not be suitable for you.

**Comment by brielletilson** [comment]
Yeah I was using ‘.xyz’ but Github wasn’t allowing me to upload that type of file so I uploaded it as a txt file so that you could have the xyz coordinates. And I originally did have the header with the name and number of atoms and tried that but it did not work so I tried it again without the headers and # of atoms and still got the same error message. But now that I have upgraded to Python 3.9.1 I no longer have that error message.

After upgrading I then got the error message “No module named ’numpy’” even though I did just update it as you can see in my previous message. And as might be able to see in the previous message, I did try running the script with python 3.9 so I am not sure where the error lies? Somehow it is not recognizing that I do actually have numpy?

**Comment by brielletilson** [comment]
Found out that I had to just uninstall numpy with ‘pip3 uninstall numpy’ and then reinstall it again with ‘pip3 install numpy' and reinstall my scipy with ‘pip3 install scipy'. Thank you for your help! I got it to work :)

**Comment by nbehrnd** [comment]
Because of GitHub's constraints, files other than .txt are best
wrapped into a .zip archive and then deposit in a running session
of GitHub.

On occasion, .xyz are not fit for calculate_rmsd.py because some
programs export e.g., the coordinates as tab delimited.  This may
be an obstacle to work this script which may be resolved by passing
said questionable .xyz file to openbabel.  So far, the rewritten
output obtained by an instruction in pattern of

obabel -ixyz input.xyz -oxyz -O output.xyz

was better because openbabel writes columns are of equal width,
padded by explicit spaces.

For the last point, I speculate from what I see in Linux Debian and
assume MacOS's software management possibly again is similar:  With
the transition of Python2 to Python3, many Python modules and
libraries equally updated their design.  To ease their discern from
legacy versions (which anticipate Python2), the newer ones often are
presented as e.g., python3-numpy, or python3-scipy.
