### ISSUE TITLE
be aware of reflection operation

### ISSUE THREAD

**Issue by SingletC** [charnley/rmsd#76]
reflection operation would not be aligned after centered or  kabsch rotation.

**Comment by nbehrnd** [comment]
Dear SingletC,

you are welcome to report errors by calculate_rmsd.py's action, issues
when using the script in general, etc.  To facilitate the replication
of your observation(s), consider the addition of a typical set of data
leading to the problem encountered.  For this purpose, a .zip archive
with the .xyz/.pdb files in question read/written by the script is a
convenient container to keep them all in one place in common.
Contrasting to .xyz/.pdb files, archives in the .zip format are
accepted by GitHub's interface of discussion, too.

Please note, because e-mail attachments typically do not pass and
enter GitHub's interface of discussion, this edit requires a running
session in GitHub.

**Comment by charnley** [comment]
@SingletC,
The reflection function is only used as an approximation to finding the atom-pairs coupled with a reorder_method, before rotation. 

Do you have a specific example where alignment fails?

**Comment by SingletC** [comment]
I got it now, Thanks
