### ISSUE TITLE
Incorrect values for proteins

### ISSUE THREAD

**Issue by KingisNitro** [charnley/rmsd#91]
Hi there, so I'm not sure where exactly to put this - and it might be my fault - but I am having problems with some protein comparisons.

I have taken the protein 1L14 from PDB, taken the sequence and ran it through AlphaFold to see how it folds. I've also ran the 1L14 through Rosetta scoring function just to have it attach the missing hydrogens so they can be compared with the AlphaFold results. AlphaFold gave some nice results, which I've compared through PyMol and that gives me RMSD of 0.393. I'm submitting all of them here (original 1L14 ; 1L14 with hydrogens as given by Rosetta; and the best AlphaFold result) as TXT files, since PDBs cannot be uploaded.

[1L14.txt](https://github.com/charnley/rmsd/files/9233905/1L14.txt)
[1L14-withH.txt](https://github.com/charnley/rmsd/files/9233906/1L14-withH.txt)
[ranked_0.txt](https://github.com/charnley/rmsd/files/9233883/ranked_0.txt)

However, when I use `calculate_rmsd --reorder 1L14-withH.pdb ranked_0.pdb` to get the result, I am getting RMSD of 10.84, and using `--no-hydrogen` does not make it much better (10.82). This value is about 30 times higher than what PyMol gives me. 

My question is how, why, and is it my mistake? Or have I missed something? The structure has 164 residues and around 2400 atoms, so it cannot be that I forgot to divide by something. Test examples work fine (ethane/translated ethane gives me something very close to zero). Thanks for any help.

**Comment by KingisNitro** [comment]
Ok something weird's going on, I tried turning the latter two into XYZ files using babel and now I'm getting the same RMSD with `calculate_rmsd` and 24.913 with PyMol. It's as if the programs... were not able to align the structures for whatever reason.
[1L14-withH.txt](https://github.com/charnley/rmsd/files/9234010/1L14-withH.txt)
[ranked_0.txt](https://github.com/charnley/rmsd/files/9234011/ranked_0.txt)

**Comment by KingisNitro** [comment]
Ok so I have aligned both files to 1L14-withH.xyz and had it print the coordinates to visualize. And this is its idea of the alignment. Which, probably a different setting would be better (hadn't played around with those yet), but it's a weird result anyway...
![alignment](https://user-images.githubusercontent.com/25939167/182158094-482a729a-71e5-4d3e-ba18-2db2e49bbbfc.png)

**Comment by charnley** [comment]
It can be complicated to align protein structures. I would recommend aligning in alpha-carbon (backbone) of the protein.

Does PyMol note which atoms reorder and alignment is done for? I have previously seen PyMol skip atoms (many years ago though)
After the alignment with pymol, can you save the reordered and aligned structures from pymol and upload them? Then do `calculate_rmsd --rotation none a.xyz b.xyz` on the structure. If PyMol has given you the correct RMSD, then the resulting RMSD should be the same.

However, It is well known that the default reorder method (Distance-based Hungarian-assignment) has cases that completely fail (see https://github.com/charnley/rmsd/blob/master/tests/test_reorder_qml.py). This is because the distance assignment fails when molecules are not already aligned (yes, there is a circular problem here). The is sometimes fixed by aligning the structure with the inertia vector

    > calculate_rmsd a.xyz b.xyz --reorder --reorder-method inertia-hungarian

but I checked, and it doesn't help your case. 

Note, If I only align the Sulfur atoms in your structure, the lowest I get is 0.46. Which is still higher than 0.39 from PyMol, which takes all atoms into account?

**Comment by KingisNitro** [comment]
Hi, thanks for the response.
We've found out a few things today with a colleague;
- PyMol actually deletes outliers that are too far upon alignment and then realigns again with the new set, and the align method does 5 cycles of this. In some cases, you can lose quite a few atoms before PyMol reaches the final state. When cycles is set to 0, the last two files I posted give RMSD of 2.387; when set to default (5), RMSD is 2.155. With 5 cycles, it ignoes about 60 atoms (out of 1400, in this case). I was not aware of this and it seems to make quite some difference occasionally
- indeed the problem is with reordering. PyMol knows which atoms are part of which residue within the protein and apparently does sequence alignment first (i.e. figuring out which part of protein corresponds to which part in another protein; so it knows which parts of proteins to align) and then does the actual alignment (physically). With the reordering in XYZ files, you do not know which atoms are linked together etc., so unfortunately this fails, because the program assumes the order is the same (which it isn't necessarily in proteins, because each atom is named). Assigning incorrect atoms is the reason why the structural alignment seems weird in the picture I posted.

Now that I know wherein lies the issue, I'll try to see what I can do about fixing the order. Thanks for all yout help :)

**Comment by charnley** [comment]
Hi @KingisNitro.

That sounds all very familiar. Getting 2.x for that structure is still a lot smaller than the 10.x that calculate_rmsd is able to produce. So when you find a solution for aligning the PDB structures before RMSD, please feel free to open a pull-request or add it to the discussions tab. 

I'll close the issue, but please feel free to open it again if needed.
